# Generated by Django 4.1.3 on 2022-11-27 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ereader', '0002_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author_Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=255)),
            ],
        ),
    ]
