# Generated by Django 4.1.3 on 2022-11-27 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ereader', '0010_user_collection'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author_Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ManyToManyField(to='ereader.author')),
                ('author_role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ereader.author_role')),
                ('book', models.ManyToManyField(to='ereader.book')),
            ],
        ),
    ]
