# Generated by Django 4.1.3 on 2022-11-27 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ereader', '0012_subject_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection_Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ManyToManyField(to='ereader.book')),
                ('collection', models.ManyToManyField(to='ereader.collection')),
            ],
        ),
    ]
