# Generated by Django 4.1.3 on 2022-11-28 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ereader', '0013_collection_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(default='No Description Available'),
        ),
    ]
