# Generated by Django 4.1.3 on 2022-11-29 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ereader', '0014_book_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='dob',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='author',
            name='dod',
            field=models.CharField(max_length=4),
        ),
    ]
