# Generated by Django 4.1.3 on 2022-11-29 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ereader', '0015_alter_author_dob_alter_author_dod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='lib_id',
            field=models.IntegerField(blank=True),
        ),
    ]
