# Generated by Django 4.1.3 on 2022-12-01 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ereader', '0016_alter_book_lib_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author_book',
            name='author',
            field=models.ManyToManyField(related_name='author_of_book', to='ereader.author'),
        ),
        migrations.AlterField(
            model_name='author_book',
            name='book',
            field=models.ManyToManyField(related_name='book_info', to='ereader.book'),
        ),
        migrations.CreateModel(
            name='BookMetaData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fulltext', models.TextField()),
                ('epub', models.FileField(upload_to='')),
                ('cover', models.FileField(upload_to='')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ereader.book')),
            ],
        ),
    ]
