# Generated by Django 4.1.3 on 2022-12-01 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ereader', '0017_alter_author_book_author_alter_author_book_book_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmetadata',
            name='gut_id',
            field=models.IntegerField(null=True),
        ),
    ]
