# Generated by Django 4.1.3 on 2022-12-01 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ereader', '0018_bookmetadata_gut_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmetadata',
            name='cover',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='bookmetadata',
            name='epub',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
