# Generated by Django 4.1.3 on 2022-12-04 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ereader', '0020_remove_bookmetadata_cover_remove_bookmetadata_epub'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(blank=True, to='ereader.author'),
        ),
        migrations.AddField(
            model_name='book',
            name='subject',
            field=models.ManyToManyField(blank=True, to='ereader.subject'),
        ),
        migrations.AlterField(
            model_name='author_book',
            name='author_role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='role_of_author', to='ereader.author_role'),
        ),
        migrations.AlterField(
            model_name='collection_book',
            name='book',
            field=models.ManyToManyField(related_name='book_for_collection', to='ereader.book'),
        ),
        migrations.AlterField(
            model_name='collection_book',
            name='collection',
            field=models.ManyToManyField(related_name='collection_for_book', to='ereader.collection'),
        ),
        migrations.AlterField(
            model_name='subject_book',
            name='book',
            field=models.ManyToManyField(related_name='book_for_subject', to='ereader.book'),
        ),
        migrations.AlterField(
            model_name='subject_book',
            name='subject',
            field=models.ManyToManyField(related_name='subject_for_book', to='ereader.subject'),
        ),
    ]
