# Generated by Django 4.1.3 on 2022-12-05 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ereader', '0020_remove_bookmetadata_cover_remove_bookmetadata_epub'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(related_name='books_by_author', through='ereader.Author_Book', to='ereader.author'),
        ),
        migrations.AddField(
            model_name='book',
            name='collections',
            field=models.ManyToManyField(related_name='books_by_collection', through='ereader.Collection_Book', to='ereader.collection'),
        ),
        migrations.AddField(
            model_name='book',
            name='subjects',
            field=models.ManyToManyField(related_name='books_by_subject', through='ereader.Subject_Book', to='ereader.subject'),
        ),
        migrations.RemoveField(
            model_name='author_book',
            name='author',
        ),
        migrations.AlterField(
            model_name='author_book',
            name='author_role',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='ereader.author_role'),
        ),
        migrations.RemoveField(
            model_name='author_book',
            name='book',
        ),
        migrations.RemoveField(
            model_name='collection_book',
            name='book',
        ),
        migrations.RemoveField(
            model_name='collection_book',
            name='collection',
        ),
        migrations.RemoveField(
            model_name='subject_book',
            name='book',
        ),
        migrations.RemoveField(
            model_name='subject_book',
            name='subject',
        ),
        migrations.AddField(
            model_name='author_book',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='ereader.author'),
        ),
        migrations.AddField(
            model_name='author_book',
            name='book',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='ereader.book'),
        ),
        migrations.AddField(
            model_name='collection_book',
            name='book',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='ereader.book'),
        ),
        migrations.AddField(
            model_name='collection_book',
            name='collection',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='ereader.collection'),
        ),
        migrations.AddField(
            model_name='subject_book',
            name='book',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='ereader.book'),
        ),
        migrations.AddField(
            model_name='subject_book',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='ereader.subject'),
        ),
    ]
