# Generated by Django 4.1.3 on 2022-12-05 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ereader', '0021_book_authors_book_collections_book_subjects_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author_book',
            name='author',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='ereader.author'),
        ),
        migrations.AlterField(
            model_name='author_book',
            name='book',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='ereader.book'),
        ),
        migrations.AlterField(
            model_name='collection_book',
            name='book',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='ereader.book'),
        ),
        migrations.AlterField(
            model_name='collection_book',
            name='collection',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='ereader.collection'),
        ),
        migrations.AlterField(
            model_name='subject_book',
            name='book',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='ereader.book'),
        ),
        migrations.AlterField(
            model_name='subject_book',
            name='subject',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='ereader.subject'),
        ),
    ]
