# Generated by Django 4.1.3 on 2022-12-04 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ereader', '0021_book_author_book_subject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='collection',
            field=models.ManyToManyField(blank=True, related_name='book_collection', to='ereader.collection_book'),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(blank=True, related_name='book_author', to='ereader.author_book'),
        ),
        migrations.AlterField(
            model_name='book',
            name='subject',
            field=models.ManyToManyField(blank=True, related_name='book_subject', to='ereader.subject_book'),
        ),
    ]
