# Generated by Django 4.1.3 on 2022-12-05 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ereader', '0022_alter_author_book_author_alter_author_book_book_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author_book',
            name='author_role',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='ereader.author_role'),
        ),
    ]
