# Generated by Django 4.1.3 on 2022-12-04 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ereader', '0022_book_collection_alter_book_author_alter_book_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.RemoveField(
            model_name='book',
            name='collection',
        ),
        migrations.RemoveField(
            model_name='book',
            name='subject',
        ),
    ]
