# Generated by Django 4.1.3 on 2022-12-05 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ereader', '0023_alter_author_book_author_role'),
        ('ereader', '0023_remove_book_author_remove_book_collection_and_more'),
    ]

    operations = [
    ]
