# Generated by Django 4.1.3 on 2022-12-07 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ereader', '0024_merge_20221205_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover_url',
            field=models.TextField(default='No Cover Available'),
        ),
    ]
